# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'syngen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_syngen_diaglog(object):
    def setupUi(self, syngen_diaglog):
        syngen_diaglog.setObjectName("syngen_diaglog")
        syngen_diaglog.resize(400, 217)
        self.buttonBox = QtWidgets.QDialogButtonBox(syngen_diaglog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 160, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.RickerList = QtWidgets.QComboBox(syngen_diaglog)
        self.RickerList.setGeometry(QtCore.QRect(110, 120, 241, 22))
        self.RickerList.setObjectName("RickerList")
        self.RickerList.addItem("")
        self.RickerList.addItem("")
        self.wavelet_type_label = QtWidgets.QLabel(syngen_diaglog)
        self.wavelet_type_label.setGeometry(QtCore.QRect(20, 120, 71, 21))
        self.wavelet_type_label.setObjectName("wavelet_type_label")
        self.max_time_label = QtWidgets.QLabel(syngen_diaglog)
        self.max_time_label.setGeometry(QtCore.QRect(20, 80, 71, 21))
        self.max_time_label.setObjectName("max_time_label")
        self.time_int_label = QtWidgets.QLabel(syngen_diaglog)
        self.time_int_label.setGeometry(QtCore.QRect(20, 40, 81, 21))
        self.time_int_label.setObjectName("time_int_label")
        self.time_int_input = QtWidgets.QTextEdit(syngen_diaglog)
        self.time_int_input.setGeometry(QtCore.QRect(110, 40, 241, 21))
        self.time_int_input.setOverwriteMode(False)
        self.time_int_input.setObjectName("time_int_input")
        self.max_time_input = QtWidgets.QTextEdit(syngen_diaglog)
        self.max_time_input.setGeometry(QtCore.QRect(110, 80, 241, 21))
        self.max_time_input.setObjectName("max_time_input")

        self.retranslateUi(syngen_diaglog)
        self.buttonBox.accepted.connect(syngen_diaglog.accept)
        self.buttonBox.rejected.connect(syngen_diaglog.reject)
        QtCore.QMetaObject.connectSlotsByName(syngen_diaglog)

    def retranslateUi(self, syngen_diaglog):
        _translate = QtCore.QCoreApplication.translate
        syngen_diaglog.setWindowTitle(_translate("syngen_diaglog", "Dialog"))
        self.RickerList.setItemText(0, _translate("syngen_diaglog", "Ricker"))
        self.RickerList.setItemText(1, _translate("syngen_diaglog", "Ormsby"))
        self.wavelet_type_label.setText(_translate("syngen_diaglog", "Wavelet Type:"))
        self.max_time_label.setText(_translate("syngen_diaglog", "Max Time (s)"))
        self.time_int_label.setText(_translate("syngen_diaglog", "Time Interval (s)"))
        '''self.time_int_input.setHtml(_translate("syngen_diaglog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))'''
        self.time_int_input.setPlaceholderText(_translate("syngen_diaglog", "0.001"))
        '''self.max_time_input.setHtml(_translate("syngen_diaglog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))'''
        self.max_time_input.setPlaceholderText(_translate("syngen_diaglog", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    syngen_diaglog = QtWidgets.QDialog()
    ui = Ui_syngen_diaglog()
    ui.setupUi(syngen_diaglog)
    syngen_diaglog.show()
    sys.exit(app.exec_())
